### ISSUE TITLE
Multiple errors running scripts/run.all.sh

### ISSUE THREAD

**Issue by acp19tag** [kris927b/SkillSpan#1]
I have followed your instructions up to 'bash scripts/run.all.sh' but am getting multiple errors at this point.

Looks like a combination of:

-  machamp errors (extra parameters passed to MachampPretrainedTransformerMismatchedEmbedder), 
-  broken links to model checkpoints (can't load config for '/data/job-postings/SpanBERT/checkpoint/') 
-  missing data that should be in 'data/Skills/' (e.g. corpus_house_large_doc_split.conll) 

stdout and stderr are attached.

[err.txt](https://github.com/kris927b/SkillSpan/files/9054727/err.txt)
[out.txt](https://github.com/kris927b/SkillSpan/files/9054728/out.txt)

Other notes:

- I'm using the same version of allennlp as in the requirements.txt (1.3).
- It looks like the de-identified data files hosted on Google Drive were given the affix 'skillspan_', but the code appears to call the same files with the affix 'corpus_'. I made this adjustment in my code.

**Comment by jjzha** [comment]
Hi Tom,

Thanks for your message: 
  - I'm not sure about the machamp related errors but perhaps these errors come from the broken links?
  - For the broken links, in `configs\` could you change in the file for whatever model you want to use .e.g., `spanbert.*.json` the link to the huggingface model? Since I uploaded our pre-trained spanbert model as well, this should be `jjzha/spanbert-base-cased`.

Let me know if this resolves the issues. I will edit the links in the near future.

Thanks!

**Comment by jjzha** [comment]
Hi Tom,

I have made two modifications:

  1. I now added the new config files for the models. The change you made with the prefix "skillspan_" is correct.
  2. I have a new version of the `.conll` files, because they were incorrectly formatted.

**Comment by acp19tag** [comment]
Hi Mike, 

Thanks for doing that!

The config files for jobspanbert have the directory as `"jjzha/jobspanbert-base-cased/"`, but this should be `"jjzha/jobspanbert-base-cased"` (without the final forward slash) or the model .config can't be found. 

Unfortunately the allennlp.common.checks.ConfigurationError still occurs with the updated model addresses:

`allennlp.common.checks.ConfigurationError: Extra parameters passed to MachampPretrainedTransformerMismatchedEmbedder: {'last_layer_only': True}`

Removing this parameter from the .config file introduces a new error:

`File "/home/acp19tag/SkillSpan/machamp/machamp/modules/pretrained_transformer_embedder.py", line 81, in __init__
    if len(layers_to_use) > 1 or layers_to_use != [-1]:
TypeError: object of type 'NoneType' has no len()`

Additionally, there is still a missing data file:

`FileNotFoundError: [Errno 2] No such file or directory: 'data/Skills/corpus_house_large_doc_split.conll'`

stdout and stderr files are attached for reference.
[err.txt](https://github.com/kris927b/SkillSpan/files/9062767/err.txt)
[out.txt](https://github.com/kris927b/SkillSpan/files/9062768/out.txt)

Thanks so much for your time!

**Comment by acp19tag** [comment]
Regarding the MachampPretrainedTransformerMismatchedEmbedder - is it possible that the allennlp model has been updated since this project ran?

**Comment by jjzha** [comment]
Hi Tom, the `corpus_house_large_doc_split.conll` were our Longformer experiments, for which I don't know where the files are now. Regardless, the results of the Longformer weren't that adequate. Hence, I now removed it from the repository. 

I'm not seeing that the directory for the config files has a slash  for jobspanbert. Did you pull the new version? From my side I got it running again:

`2022-07-08 04:19:15,193 - INFO - allennlp.training.trainer - Epoch 0/19
2022-07-08 04:19:15,193 - INFO - allennlp.training.trainer - Worker 0 memory usage: 3.5G
2022-07-08 04:19:15,194 - INFO - allennlp.training.trainer - GPU 0 memory usage: 414M
2022-07-08 04:19:15,194 - INFO - allennlp.training.trainer - Training
  0%|          | 0/151 [00:00<?, ?it/s]
.run/Skills/span_f1: 0.0063, .run/.sum: 0.0063, batch_loss: 1939.6017, loss: 1273.7016 ||:   7%|7         | 11/151 [00:02<00:28,  4.92it/s]
`

I achieved this by installing the `requirements.txt` from machamp.

Let me know if you manage!

**Comment by acp19tag** [comment]
Thank you! This works for most of the models. 

I'm still getting the error message when training bert and jobbert:

`allennlp.common.checks.ConfigurationError: Extra parameters passed to MachampPretrainedTransformerMismatchedEmbedder: {'last_layer_only': True}`

Additionally, there doesn't appear to be a `machamp/logs/` directory, which means I can't run the `scripts/run.predict.sh` on any of the models. 

As well, training spanbert didn't create a `data/spanbert/` directory, so I can't run `scripts/run.evaluate.sh spanbert`.

Any ideas on how to fix?

**Comment by jjzha** [comment]
For your first two errors, for some reason, my edits to the config files didn't save and for now, it should work for all.

I edit the path of `machamp/logs` to just `logs` as it will create it in your root project directory. 

For your last issue, I believe the path for `data/*/` should be `logs/*/`, I changed it in `scripts/run.evaluate.sh *`, let me know if it works!

**Comment by acp19tag** [comment]
Fantastic, thanks so much!
