### ISSUE TITLE
Hugging face

### ISSUE THREAD

**Issue by TijanaTL** [kris927b/SkillSpan#10]
Which task should I use in a pipeline to get same results as in the paper?

**Comment by jjzha** [comment]
Hi Tijana, if you want to reproduce most things you would have to run it in this order:

  1. bash scripts/run.all.sh
  2. bash scripts/run.predict.all.sh
  3. bash scripts/run.evaluate.sh

Note that the results might differ slightly as we didn't release the `big` subset, as it is proprietary data.
