### ISSUE TITLE
Single-task learning includes multi-task labels

### ISSUE THREAD

**Issue by ribenamaplesyrup** [kris927b/SkillSpan#14]
I've noticed that models fine-tuned for single-task learning include both skills and knowledge labels in their predictions. For example, if I run the task `bash scripts/run.experiment.sh bert skills` it will run 5 seed experiments creating folders in logs for `skill.bert.skills1`, `skill.bert.skills.2` etc. If I then attempt to predict on dev and test sets with `bash scripts/run.predict.sh bert skills dev` it produces files like `skills.tech.dev.1.out` with predictions for both skills and knowledge labels even though the model should have only been fine-tuned for skills. Here is an example prediction from `skills.tech.dev.1.out`:

```
The	O	O
ideal	O	O
candidate	O	O
will	O	O
have	O	O
a	O	O
desire	O	O
to	O	O
be	O	O
at	B-Skill	O
the	I-Skill	O
forefront	I-Skill	O
of	I-Skill	O
change	I-Skill	O
and	O	O
a	O	O
real	O	O
passion	O	O
for	O	O
DevOps!	O	B-Knowledge
```

Is this to be expected?

**Comment by ribenamaplesyrup** [comment]
I've also realised these column values are the same across all `.out` files for different seeds so thinking they must be dummy values rather than values the model actually predicted?

**Comment by jjzha** [comment]
This is interesting behavior. I forgot whether this was the case for us..., for now could you just ignore the extra predicted column? Hope this is not impeding your experiments too much.

**Comment by kris927b** [comment]
I remember this as being machamp simply copying the gold labels from the input file to the output file for columns that are not predicted.
Could you check if the knowledge tags are the same in input and output?

**Comment by ribenamaplesyrup** [comment]
Yeah looks like they are the same. Thank you @jjzha and @kris927b!
