### ISSUE TITLE
problems running run.evaluate.sh (e.g., arg mismatch vs. evaluate.py)

### ISSUE THREAD

**Issue by tohara-PandoLogic** [kris927b/SkillSpan#3]
When trying to reproduce the evaluation results mentioned in your paper, I ran into a problem with the way arguments are specified in run.evaluate.sh versus what evaluate.py expects. The Bash script uses --gold_file to indicate the ground truth, but the Python script assumes this is given by the first argument.

Here's how I got a simple invocation to work (using 1 or 5 random runs):

```
$ python3  scripts/evaluate.py  data/jobbert/knowledge.tech.test.1.out --gold_file=data/Skills/skillspan_tech_test.conll
    =>
$ python3  scripts/evaluate.py  data/Skills/skillspan_tech_test.conll  data/jobbert/knowledge.tech.test.1.out
```

In addition, I had similar problems with the specification of the data and logs paths in run.evaluate.sh, as mentioned in #1. Will a revised master evaluation script be available?

Best,
Tom

p.s., Thanks very much for making the code and data available for Skill Span!

**Comment by jjzha** [comment]
Hi Tom,

Thanks for pointing that out! It should be resolved by now. For the path issues, which path is incorrect?

Best,
Mike

**Comment by tomasohara** [comment]
Thanks for fixing the argument specification.

The path-related problems deal with GPATH and PPATH.
```
GPATH="data/Skills/"
PPATH="logs/$MODEL"
...
   python3 scripts/evaluate.py $GPATH/corpus_"$site"_test"$EXTRA".conll $PPATH/$method.$site.test.1.out ... $PPATH/$method.$site.test.5.out

```

Specifically:
- no data/Skills/corpus_*; instead data/Skills/skillspan_*
- no logs/jobspanbert; instead logs/skill.jobspanbert.knowledge.1, etc.
- prediction results stored under ./data, not ./logs
  ex: data/jobbert/knowledge.tech.test.1.out
  note: there are prediction results under ./logs but a different file naming convention is used
  ex: logs/skill.jobbert.knowledge.5/2022.07.24_10.34.29/tech.dev.out

**Comment by jjzha** [comment]
Thank you for the pointers.

I made a couple of changes: 

- ` data/Skills/corpus_*` > `data/Skills/skillspan_*`
- modified paths to grab the predictions results from `./data`

The predictions in `./logs` are on the development set.

Let me know if this works.

Best,
Mike

**Comment by tohara-PandoLogic** [comment]
Thanks for the fix. I’ll try to test it tomorrow.

[deleted all the extraneous text introduced via email-based reply]

note to self: don't reply via email! ;)

**Comment by tohara-PandoLogic** [comment]
That didn't work. Here's the current issue:

```
$ scripts/run.evaluate.sh bert
...
Evaluating bert house on Skills
Traceback (most recent call last):
...
FileNotFoundError: [Errno 2] No such file or directory: 'data/bert/Skills.house.test.1.out'
```

This gets resolved by changing "Skills" to "skills":
```
git diff run.evaluate.sh | less
...
-for method in Skills Knowledge Multi
+for method in skills knowledge multi
```

However, I am still have problems with the required output files not being present. This is due to prediction not being run in the master script (i.e., run.all.sh). I'll create separate tickets regarding run.all.sh and README.md to clarify the problems. As is, it is quite confusing how to do a reproduce a complete end-to-end example (e.g., just for jobbert for knowledge).

**Comment by jjzha** [comment]
Thanks, Tom! This should be resolved in [b229048](https://github.com/kris927b/SkillSpan/commit/b22904822aecc4946a1f5f441ab9c16346e97cef). Let me get to your next issue.

**Comment by jjzha** [comment]
Hi Tom, 

I modified the scripts and re-ran everything. The sequence is as follows:

1. `bash scripts/run.all.sh`. This will run everything till prediction.
2. `bash scripts/run.predict.all.sh`. Will run inference of all models on all sets.
3. `bash scripts/run.evaluate.sh`. Should create performance measures in `metrics/`

Let me know if this works.

M.

**Comment by tohara-PandoLogic** [comment]
Thanks. Note that I will need to rerun everything from scratch (e.g, 1+ day for training proper), so I will let you know later in the week.\

**Comment by tohara-PandoLogic** [comment]
That's much better now, thanks.
