### ISSUE TITLE
inconsistent device specification in scripts

### ISSUE THREAD

**Issue by tomasohara** [kris927b/SkillSpan#4]
Most of the SkillSpan scripts use --device 0 when invoking machamp. However, run.indiviual.sh uses --device 1. For consistency, the same device should be used.

Note that it seems even better to omit the device specification, as PyTorch has automatic device selection. I did a test of this, it seems to work in my two-GPU setup.

Best,
Tom

**Comment by jjzha** [comment]
Hi Tom,

Awesome, thank you for pointing out the flags and also thank you for the tip, I thought we still had to manually select the device. I revised the scripts. I'll mark this as solved.

Best,
Mike
