### ISSUE TITLE
How to run Jobbert as a quick example

### ISSUE THREAD

**Issue by chalagashvili** [kris927b/SkillSpan#5]
Hi there, this is not an issue but a question. Sorry if you have some other channel for questions and I do not know. Basically what I am looking for is an example how I can run `https://huggingface.co/jjzha/jobbert-base-cased` quickly to just see how good the existing model at Huggingface is. I would provide a job description and to see the extracted skills. Is there a quick way to see this somehow? 

I tried to train models myself at google colab with GPU enabled `torch.cuda.is_available()` outputting `true` . Installed requirements as provided in Readme and then ran:

`bash scripts/run.individual.sh jobbert skills 1`

Unfortunately I receive a torch gpu error below:

```
Training jobbert on skills
/root/.local/lib/python3.7/site-packages/torch/cuda/__init__.py:52: UserWarning: CUDA initialization: Unexpected error from cudaGetDeviceCount(). Did you run some cuda functions before calling NumCudaDevices() that might have already set an error? Error 803: system has unsupported display driver / cuda driver combination (Triggered internally at  /pytorch/c10/cuda/CUDAFunctions.cpp:100.)
  return torch._C._cuda_getDeviceCount() > 0
```
So the training is done with CPU, and it tells me that approximate training time is 6 hours+.. I can't wait that much (with my internet being unstable..)

Or maybe if you could provide a `jobbert skills` model that would work also.

**Comment by jjzha** [comment]
Hi,

Not sure what triggered the error, but could you try running the line in `run.individual.sh` as standalone and explicitly with the `--device` flag?

This would be in your case:

`python3 machamp/train.py --dataset_config configs/Skills/skills.json --parameters_config configs/Skills/jobbert.1.json --name skill.jobbert.skills.1 --device 0`

Let me know if this works.

**Comment by chalagashvili** [comment]
The script that you provided worked without errors and is training is now running with GPU. Thank you!
