### ISSUE TITLE
add prediction and evaluation steps to run.all.sh

### ISSUE THREAD

**Issue by tohara-PandoLogic** [kris927b/SkillSpan#6]
It is currently tedious to reproduce the evaluation in the paper because run.all.sh does not invoke run.predict.sh nor run.evaluate.sh.

This can be done as follows:
```
$ diff --context=1 /tmp/SkillSpan/scripts/run.all.sh .
...
               scripts/run.experiment.sh $model $exp
+
+              for set in dev test
+              do
+                         scripts/run.predict.sh $model $exp $set
+              done
+
+              scripts/run.evaluate.sh $model
```

note: This will produce the necessary data files needed for #3 (e.g., data/bert/skills.tech.test.2.out).

**Comment by jjzha** [comment]
Thanks a lot again, Tom. It was more intended to do it separately. As shown in the [QA](https://github.com/machamp-nlp/machamp/blob/8c54d152167357bfa62c164cff87e9067cef44c6/README.md?plain=1#L234) of the authors of MaChAmp. However, feel free to keep using your version of the `run.all.sh` script.
