### ISSUE TITLE
clarify README.md by mentioning dependencies

### ISSUE THREAD

**Issue by tomasohara** [kris927b/SkillSpan#7]
Currently, running the examples in README.md file is complicated because there are some subtle dependencies in the steps. For example, before evaluation can be done for a particular model (e.g., jobbert), the prediction step must be run for each combination of method (i.e., {skills, knowledge, multi}) and source (i.e., {house, tech}).

Part of this would be resolved by the suggestion in #6 runs the prediction and evaluation automatically. However, it would still be good to show the necessary input files for prediction and evaluation. This would be tedious to do by hand, but you can modify the scripts to trace the command invocations (e.g., via 'set -o xtrace').

For example, the input for prediction and evaluation for jobbert on knowledge from tech follows:
```
python3 machamp/predict.py logs/skill.jobbert.knowledge.1/2022.07.23_14.04.47/model.tar.gz data/Skills/skillspan_tech_test.conll data/jobbert/knowledge.tech.test.1.out --dataset tech --device 0

python3 scripts/evaluate.py data/Skills/skillspan_tech_test.conll data/jobbert/knowledge.tech.test.1.out data/jobbert/knowledge.tech.test.2.out data/jobbert/knowledge.tech.test.3.out data/jobbert/knowledge.tech.test.4.out data/jobbert/knowledge.tech.test.5.out
```

Aside: I added the following to each script to support conditional tracing based on TRACE_BASH environment variable:
```
# Optionally enable tracing of command invocations
if [ "$TRACE_BASH" = "1" ]; then set -o xtrace; fi
```

**Comment by jjzha** [comment]
Hi Tom,

I made it such that now you need to run 3 bash scripts in sequence. This is indicated in https://github.com/kris927b/SkillSpan/issues/3#issuecomment-1214212191

In the README, I added some examples on what the possible variables can be (e.g., $MODEL and such).

**Comment by tohara-PandoLogic** [comment]
Thanks, that's clearer.
