### ISSUE TITLE
evaluation output file under ./metrics doesn't distinguish model

### ISSUE THREAD

**Issue by tohara-PandoLogic** [kris927b/SkillSpan#8]
The output filename produced by evaluate.py  doesn't distinguish the model, causing runs for spanbert and jobspanbert to use the same filename.

Here is the problem:
```
     model_name = pred_files[0].split("/")[2]
=>
     model_name = pred_files[0].split("/")[1]
```

This can be seen by examining how the split is done:
```
In [43]: pred_files = ["data/jobspanbert/skills.house.test.1.out"]; print(pred_files[0].split("/"))
['data', 'jobspanbert', 'skills.house.test.1.out']

In [44]: pred_files[0].split("/")[2] == pred_files[0].split("/")[-1]
Out[44]: True
```
As a result, only 6 of the 24 output files were present under the ./metrics directory:

```
$ ls ../metrics/ | grep -v bert | grep -i tech.*knowledge
tech.knowledge.knowledge.tech.test.1.out.test.json

$ ls ../metrics/ | grep bert | grep -i tech.*knowledge
tech.knowledge.bert.test.json
tech.knowledge.jobbert.test.json
tech.knowledge.jobspanbert.test.json
tech.knowledge.spanbert.test.json
```

**Comment by jjzha** [comment]
Hi Tom,

This should be resolved in https://github.com/kris927b/SkillSpan/issues/3#issuecomment-1214212191

Let me know if this is the case.

**Comment by tohara-PandoLogic** [comment]
That works now: 24 files in the metrics directory. Thanks.
