### ISSUE TITLE
problem running prediction over new files (in new tag-all-files.bash)

### ISSUE THREAD

**Issue by tomasohara** [kris927b/SkillSpan#9]
I ran into a subtle problem with a script for tagging arbitrary files (i.e., not part of experiment): see tag-all-files.bash. Running input through the tech and house sources yield the same results.

I isolated the issue to the following, which produces the same tagging even though different sources:
```
python -u machamp/predict.py  $(ls -t logs/skill.jobspanbert.skills.1/*/model.tar.gz | head -1)  data/Skills/skillspan_tech_train.conll  temp/skillspan_tech_train-tech.out  --dataset tech >| temp/skillspan_tech_train-tech.take1.log 2>&1

python -u machamp/predict.py  $(ls -t logs/skill.jobspanbert.skills.1/*/model.tar.gz | head -1)  data/Skills/skillspan_tech_train.conll  temp/skillspan_tech_train-house.out  --dataset house >| temp/skillspan_tech_train-house.take1.log 2>&1
```

However, if the model file is copied, then the taggings differ:
```
/bin/cp -fp $(ls -t ../logs/skill.jobspanbert.skills.1/*/model.tar.gz) .

python ../machamp/predict.py model.tar.gz  ../data/Skills/skillspan_tech_train.conll  skillspan-tech.out --dataset tech >| skillspan-tech.log 2>&1

python ../machamp/predict.py model.tar.gz  ../data/Skills/skillspan_house_train.conll  skillspan-house.out --dataset house >| skillspan-house.log 2>&1
```
See the attached files for output.
[_skillspan-predict-workaround.05oct22.log](https://github.com/kris927b/SkillSpan/files/9720775/_skillspan-predict-workaround.05oct22.log)
[_skillspan-predict-workaround.sh.txt](https://github.com/kris927b/SkillSpan/files/9720776/_skillspan-predict-workaround.sh.txt)
[_skillspan-predict-quirk.05oct22.log](https://github.com/kris927b/SkillSpan/files/9720777/_skillspan-predict-quirk.05oct22.log)
[_skillspan-predict-quirk.sh.txt](https://github.com/kris927b/SkillSpan/files/9720778/_skillspan-predict-quirk.sh.txt)
[tag-all-files.bash.txt](https://github.com/kris927b/SkillSpan/files/9720785/tag-all-files.bash.txt)

**Comment by jjzha** [comment]
Sorry, correct me if I'm wrong Tom: You are trying to predict on the train set am I right? In the first code block, you are pointing to the same path for prediction `data/Skills/skillspan_tech_train.conll`. Let me know if I'm missing anything...

You might wanted to use `data/Skills/skillspan_house_train.conll` for the second one?

**Comment by tomasohara** [comment]
A similar problem occurs when skillspan_tech_test.conll is used. That is, the same exact scores are returned regardless of source. See the new attached output files.[
[_skillspan-predict-wordaround.11oct22.log](https://github.com/kris927b/SkillSpan/files/9761550/_skillspan-predict-wordaround.11oct22.log)
[_skillspan-predict-quirk.11oct22.log](https://github.com/kris927b/SkillSpan/files/9761551/_skillspan-predict-quirk.11oct22.log)
](url)

I think this is related to the same task name being used in knowledge.json and likewise skills.json.

> It should be noted that to do real multi-task learning, the tasks should have different names. For example, having two tasks with the name upos in two different datasets, will effectively lead to concatenating the data and threating it as one task.

via https://github.com/machamp-nlp/machamp

(Perhaps, my workaround is just a fluke as the values are still close: 0.551 vs. 0.536.)

**Comment by jjzha** [comment]
Hmm that's weird. Could you please check whether the files you copied/predicted contains different (training/test) instances? Maybe something went wrong there? I didn't run into this issue.

**Comment by tomasohara** [comment]
I'm not sure what you are suggesting. Note that I ran this on two different Skillspan installations with separate training runs, and the results are the same.

Can you try the scripts I provided? I designed them to run with the default Skillspan setup, so that it runs "out of the box". They can be run as follows:

```
cd ~/skillspan
source _revised-skillspan-predict-quirk.sh  > _revised-skillspan-predict-quirk.log 2>&1
source _revised-skillspan-predict-workaround.sh  > _revised-skillspan-predict-workaround.log 2>&1
```

Revised versions are attached.
[_revised-skillspan-predict-workaround.sh.txt](https://github.com/kris927b/SkillSpan/files/9777871/_revised-skillspan-predict-workaround.sh.txt)
[_revised-skillspan-predict-quirk.sh.txt](https://github.com/kris927b/SkillSpan/files/9777872/_revised-skillspan-predict-quirk.sh.txt)
